export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';

export const UPDATE_PROFILE_NEW = 'UPDATE_PROFILE_NEW';
export const UPDATE_PROFILE_NEW_SUCCESS = 'UPDATE_PROFILE_NEW_SUCCESS';
export const UPDATE_PROFILE_NEW_ERROR = 'UPDATE_PROFILE_NEW_ERROR';

export const UPDATE_PROFILE_NO_OTP = 'UPDATE_PROFILE_NO_OTP';
export const UPDATE_PROFILE_NO_OTP_SUCCESS = 'UPDATE_PROFILE_NO_OTP_SUCCESS';
export const UPDATE_PROFILE_NO_OTP_ERROR = 'UPDATE_PROFILE_NO_OTP_ERROR';

export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';

export const LOG_OUT_PROFILE = 'LOG_OUT_PROFILE';
export const LOG_OUT_PROFILE_SUCCESS = 'LOG_OUT_PROFILE_SUCCESS';
export const LOG_OUT_PROFILE_ERROR = 'LOG_OUT_PROFILE_ERROR';
